# This software is contributed or developed by KYOCERA Corporation.
# (C) 2011 KYOCERA Corporation
# (C) 2012 KYOCERA Corporation
# (C) 2013 KYOCERA Corporation
# (C) 2014 KYOCERA Corporation
#
obj-y	+= dnand.o

dnand-y	:= dnand_cdev_driver.o dnand_k_api.o dnand_fs.o dnand_drv.o

